### ISSUE TITLE
Report meaningful errors, not "Error talking to browserpass"

### ISSUE THREAD

**Issue by maximbaz** [browserpass/browserpass#164]
We are sick of seeing "Error talking to browserpass". Time to report meaningful errors.

--------------

UPDATE: since 2.0.18 we will have errors from the host app printed in stdout and sent to the extension. 

What needs to be done next:

- In addition to stdout, log the errors to a file, e.g. `/var/log/browserpass.log`
- Test the errors, make sure what is shown in the extension is not very cryptic.
- Create a standardized message structure for communication between extension and the host app, have separate fields for the error details and successful results.

----------

As a very first step, we should introduce logging for the host app. This way we can at least see if it was triggered or not and which actions it took.

Next step is passing error messages back to the browser. I was playing with this a little bit, it would require some refactoring. Today browserpass host app crashes on any error, and prints details on stderr. However Chrome doesn't read stderr, it only reads stdout. Also, it doesn't like crashes, on unexpected crash it prints this famous "Error talking to browserpass".

If we are going to change this, the approach would be to prevent the host app from crashing, like ever, and instead send the error message back to browser. We could come up with some standardized JSON structure, e.g. `{"status": "OK/FAIL", "messsage": "<message from host app" }` to distinguish errors from correct responses.

It is also worth keeping in mind https://github.com/dannyvankooten/browserpass/issues/20#issuecomment-297159280, as it suggests to bring this idea one step further and not only never crash the host app, but actually never even stop the connection between browser and the app. Today the connection is established and closed as needed, instead we could establish one connection and keep it open forever. Such always open connection could maybe even help with https://github.com/dannyvankooten/browserpass/issues/77#issuecomment-332673549.

One more interesting idea is to check the versions - in case of an error, among error details the host app should send its version back to the extension, so that we can additionally do a version check and suggest users to update. It is a bit tricky, because sometimes we have no changes in host app and browser extension is actually expected to work with previous version of the host app.

It doesn't have to be implemented all at once, I'm just throwing ideas in and connecting the dots 🙂

**Comment by chrboe** [comment]
`chrome.runtime.connectNative` would be a good idea in general. I know it's really not relevant for our use case, but the systems programmer in me cringes at the thought of spawning a new process for every request 🙂

**Comment by jwiegley** [comment]
I would love this, btw. I find that browserpass works some of the time when I'm testing to see if it works, but almost never when I actually need it. The thing is, I have no idea what the problem might even be, or where, because there's nothing in any log. Is it the extension? Communication? The external utility? My password database? Even a clue would help to narrow down why it sometimes works but mostly doesn't...

**Comment by maximbaz** [comment]
I feel your pain. Would you like to help implementing this request? I'd be happy to test and review a PR.

We could start with making sure error logs are appended to some log file in addition to being printed in STDERR. It might be as easy as to configure the log to do so, or if the default logger doesn't support so, switching to some kind of more powerful logger, like [logrus](https://github.com/sirupsen/logrus).

Looks like there are only two places where errors can be logged in the entire codebase:

https://github.com/dannyvankooten/browserpass/blob/46034e720ac361bc9499f7a4ae0681f061b11e8a/cmd/browserpass/main.go#L17-L24

**Comment by jwiegley** [comment]
@maximbaz Sure, I'll help out. I've never used Go before, but I can add print statements like a champion. :)

**Comment by jwiegley** [comment]
@maximbaz I wonder if this is a sandboxing issue. If I run Firefox by executing "firefox-bin" from the Terminal (in order to see stderr), it always works. But if I run it as a graphical application from the Dock, that's when I have problems.

**Comment by maximbaz** [comment]
If you have macOS, that is a very popular issue - see #13, #197, #175 and many others, #13 is the main thread for that issue 🙂

**Comment by jwiegley** [comment]
@maximbaz I just found that old issues independently. Trying the wrapper script approach now, it seems to be working.

**Comment by jwiegley** [comment]
@maximbaz Just to confirm again: after a day of use, I've been unable to get browserpass to break.  Here's the script I used to replace `firefox` and `firefox-bin` in my `Contents/MacOS` folder of the Firefox application (after moving them to `.firefox` and `.firefox-bin`):

``` bash
#!/bin/bash
source /etc/bashrc
dir=$(dirname "$0")
exec "$dir"/.firefox "$@"
```

**Comment by maximbaz** [comment]
Although now perfect yet, this is much better in Browserpass v3, thus closing.
