### ISSUE TITLE
Error: Specified native messaging host not found.

### ISSUE THREAD

**Issue by Loki-Afro** [browserpass/browserpass#258]
### General information

* Fedora 28:
* Chrome 66.0.3359.139:
* Information about the host app:
  * How did you install it?
    * Installed via a package manager, downloaded a pre-built binary, compiled yourself?
Installed via App Store
  * Browserpass extension version as reported by your browser:
2.0.21
---

### Exact steps to reproduce the problem
1. click on the plugin

### What should happen?
don't know ;D

### What happened instead?
Displays a text: "Error: Specified native messaging host not found."

**Comment by maximbaz** [comment]
Extension is only part of the browserpass, you also have to install the native app for everything to work properly 😉 

https://github.com/browserpass/browserpass#installing-the-host-application

**Comment by Loki-Afro** [comment]
@maximbaz thanks for the hint

it works on fedora 28 when installing the rpms from https://copr.fedorainfracloud.org/coprs/akahl/browserpass/ even if it is not officially supported...

**Comment by maximbaz** [comment]
That's great, just curious, does it install the latest version of the native app?

```
❯ browserpass -v
Browserpass host app version: 2.0.21
```

(if `-v` doesn't print anything, it is an old version 😃)

**Comment by Loki-Afro** [comment]
@maximbaz seems like its stuck ;)

**Comment by Loki-Afro** [comment]
@maximbaz 
installed from latest release ;)
```
zarathustra@wotan ~ % browserpass-linux64 -v
Browserpass host app version: 2.0.21
```
