### ISSUE TITLE
Browserpass fails to unlock card

### ISSUE THREAD

**Issue by benjumanji** [browserpass/browserpass#259]
### General information

* Operating system + version: Arch linux / up to date
* Browser + version: firefox / 59.0.2
* Information about the host app:
  Installed via AUR
  * If installed an official release, put a version: 
    2.0.21
* Information about the browser extension:
  Webstore, firefox.
  * Browserpass extension version as reported by your browser: 2.0.21
    

---

### Exact steps to reproduce the problem
1. Reboot
2. As for password

### What should happen?

Password should be copied to clipboard

### What happened instead?

GPG2 error, no secret key.

This can be remedied by unlocking the card (I use a card). Then everything works just fine. This used to work with no problems at all.

**Comment by maximbaz** [comment]
What kind of GPG2 error do you see, and how do you see it? "works for me" © 😃

**Comment by benjumanji** [comment]
Well now I don't know what to think. I killed the agent so I could screencast, and now rather than showing any error it just doesn't fill a password. Unfortunately I can't get the screencast software to cooperate, and I have used up all my dicking around time for the day. I'll be back.

**Comment by benjumanji** [comment]
Closing because procrastination seems to have mystically solved whatever the problem was.
