### ISSUE TITLE
OTP Documentation

### ISSUE THREAD

**Issue by fernandoenzo** [browserpass/browserpass#263]
Could you please add some documentation on how to configure the OTP? Actually I'm not really sure this is what I think it's (some kind of 2FA), but I'm still curious.

Thank you for a great job, this extension made my day!

**Comment by maximbaz** [comment]
Here you go: https://github.com/tadfisher/pass-otp

This extension is only providing a UI for already configured OTP with no extra steps needed. `pass-otp` is definitely supported, maybe there are other ways to configure OTP as well (I'm not sure).
