### ISSUE TITLE
Missing prompt for GPG key (?)

### ISSUE THREAD

**Issue by comatory** [browserpass/browserpass#265]
### General information

* Operating system + version: Mac OS High Sierra
* Browser + version: Chrome 66
* Information about the host app:
  * How did you install it?
    * Installed via `brew`
  * If installed an official release, put a version: 
    * 2.0.21
* Information about the browser extension:
  * How did you install it?
    * Chrome webstore
  * Browserpass extension version as reported by your browser:
    * 2.0.21
---

### Exact steps to reproduce the problem
1. Do not use `pass` for some time
2. After some time, decrypting passwords require my GPG key password
3.  When trying to use `browserpass` extension, it reports:

```
exit status 2 gpg: no secret key found
```

### What should happen?

I'm not sure if this is correct behaviour but maybe a password prompt should popup asking for my GPG password.

### What happened instead?

Displayed error.

**Comment by maximbaz** [comment]
Hi, this should work, but it seems you are using a very old version of the host app - please install the latest version and let me know if you still have the issue.

**Comment by comatory** [comment]
OK so by the host app you probably mean browserpass host app, not `pass` itself, right?

**Comment by maximbaz** [comment]
Correct, download [here](https://github.com/browserpass/browserpass/releases/tag/2.0.21).

browserpass doesn't use `pass` at all by the way, only `gpg` to decrypt files 🙂

**Comment by comatory** [comment]
So in that I case I went ![here](https://github.com/browserpass/browserpass/releases/download/2.0.21/browserpass-darwinx64.zip) and downloaded latest release.

**Comment by maximbaz** [comment]
Yep, that's the one. Make sure to remove the old binary, there was a case when someone had two binaries installed and the old one took precedence.

**Comment by comatory** [comment]
Well that's the version I originally installed it with so I have no other binaries. It does not seem to work. How would I check (just in case) I have two binaries of the host app?

**Comment by comatory** [comment]
OK so I located file `com.dannyvankooten.browserpass.json` at `/Users/$USER_NAME/Library/Application Support/Google/Chrome/NativeMessagingHosts`. I looked into it, it looks like this:

```
{
  "name": "com.dannyvankooten.browserpass",
  "description": "Browserpass binary for the Chrome extension",
  "path": "/Users/<user_name>/Documents/browserpass-darwinx64/browserpass-darwinx64",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://naepdomgkenhinolocfifgehidddafch/",
    "chrome-extension://klfoddkbhleoaabpmiigbmpbjfljimgb/"
  ]
}
```

when I use the `path` like this `/Users/<username>/Documents/browserpass-darwinx64/browserpass-darwinx64 -v` it gives me: `Browserpass host app version: 2.0.21`

Btw I'm using Chrome with two user profiles. Both of them have `browserpass` extension.

**Comment by maximbaz** [comment]
Awesome, so what's the current status, is everything good, is everything the same as before upgrading, is it worse? 🙂

**Comment by comatory** [comment]
It's still the same. I get the same message. When I unlock password using `pass` then it works fine.

**Comment by comatory** [comment]
Could this be caused by some kind of settings on the GPG key itself? I just don't get any prompt to unlock the GPG key from the extension itself.

**Comment by maximbaz** [comment]
I have a suspicion that you are experiencing some kind of variation of #13, try these steps from FAQ: https://github.com/browserpass/browserpass#does-not-work-on-macos-native-host-has-exited

**Comment by comatory** [comment]
OK I followed FAQ and it is fixed now. I had to create `~/.gnupg/gpg.conf` and `~/.gnupg/gpg-agent.conf` files though but it's all good now it seems. Thanks.

**Comment by maximbaz** [comment]
Awesome!
