### ISSUE TITLE
Password decryption appears not to be attempted

### ISSUE THREAD

**Issue by rgammans** [browserpass/browserpass#266]
### General information

* Operating system Debian 9.1
* Browser + version: firefox-esr_60.0.2esr-1 (from debian experimental)
* Information about the host app:
  * How did you install it?
      Compiled myself; -v = "Browserpass host app version: 2.0.19"
      from commit id #4ca5c7c0d557f4aece063da54683eb04436d59be
* Information about the browser extension:
  * How did you install it?
    * Installed via webstore, downloaded a pre-built extension, compiled yourself?
       Install from the extensions tab and seaching by name inside firefox.
  * Browserpass extension version as reported by your browser:
      browserpass-ce 2.0.21
---

### Exact steps to reproduce the problem
1. Visit a sign on page
2. Click on the browerpass icon, or use the Ctrl-Shift-L hotkey
3. Search for password; if not already there (this works)
4. Click to decode and fill password.

### What should happen?
I would expect gpg to ask me for my passphrase (via the gnome-sessions gpg-agent feature) ; then the password to be decoded and filled into the password <input> on the current page.

### What happened instead?
I got busy logo for a few seconds and then the dialog box disappeared. I didn't get any gpg passphrase prompts at all.

### Some notes;
 This version of the Native host app works fine with the same extension under google-chrome. I updated the native host helper app to commit id #62bda2a62348be40ab64b2a603ae756fb5f7b869  (2.0.21+) as part wrting this bug report and I still have the same behaviour

**Comment by maximbaz** [comment]
The native app just calls the `gpg` binary, it doesn't handle gpg prompts and things like that, this is all done by gpg itself. If this works in Chrome, this suggests something is wrong with the Firefox itself in your installation — it works for me in both Chromium and Firefox.

Things to try: run Firefox from terminal, see if you get some extra error logs. Try unlocking the gpg-agent beforehand, see if Firefox able to fill passwords when gpg doesn't need passphrase anymore.

**Comment by maximbaz** [comment]
Hmm, this sounds extremely suspicious that your Firefox can make gpg to get the password, but not to show the pinentry dialog. What is the location of your `gpg` binary, full path? What is the contents of your `~/.gnupg/gpg.conf` and `~/.gnupg/gpg-agent.conf`? Try to remove the Firefox configs by purging browserpass from `/usr/lib/mozilla/native-messaging-hosts` and/or `~/.mozilla/native-messaging-hosts`, and then re-running the `install.sh` script.

**Comment by rgammans** [comment]
I've checked the communication both ways on both firefox and  chrome; also chcked the environment with a wrapper script around the host app.

While chrome is sending autoSubmit:True; and firefox autoSubmit:False;  I don't t think this is relevant as I can send the firefox request verbatim to the host app (using a python repl to ensure the binary length field is not corrupted.) and I get the password unlocked correctly.

I no see an error being returned form the hsot app in failure cases "exit status 2\ngpg: decryption failed: No secret key\n" ; but it doesn't show on the UI

Could there be some sort of very small timeout in firefox which I am hitting in some manner?

I have also tried debian's firefox 52.8.1_esr-2; and mozilla binaty download of firefox 60.0.2.
All have the same behaviour.

**Comment by maximbaz** [comment]
The reason I asked about `gpg.conf` and `gpg-agent.conf` is because macOS users have to explicitly declare `use-agent` and `pinentry` configs - see [here](https://github.com/browserpass/browserpass#does-not-work-on-macos-native-host-has-exited). I didn't have to configure that on my Arch Linux.

`autoSubmit` is something that is configured in extension options, and the default value changed at some point, that could be the cause.

Wow this is very difficult case... One more idea, try to see if you can get to a browser console, or developer tools in chromium, and see maybe browserpass is writing some error logs there. I think the link to devtools is somewhere in Addons > Debug addons.

**Comment by rgammans** [comment]
Ok; I'm seeing the following when it fails

```
18:52:42.404 exit status 2
gpg: decryption failed: No secret key
  background.js:173:13
18:52:42.401 [Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 533"  data: no]
```
(Sorry about the formatting - it's just cut and pasted from the add-on debugger console)

I'm intrigued by 1) The NS error is shown after the status - but it does have an earlier timestamp.
2) The error from the backend is getting to firefox.

If I unlock the password key  and try I get the following:-
```
18:57:56.107 Unchecked lastError value: Error: Script 'moz-extension://ebd80c62-27da-498c-8efd-554d4d2ac42d/inject.js' result is non-structured-clonable data
```

**Comment by okennedy** [comment]
I'm having exactly the same issue with PureOS (Debian-based).  This seems to be an issue with gnome-shell.  The following shows up in `journalctl -xe` after trying to get browserpass-ce to prompt for a password: 
```
Jun 30 21:35:12 Loki gnome-shell[1867]: remove_mnemonics: assertion 'label != NULL' failed
Jun 30 21:35:12 Loki gnome-shell[1867]: remove_mnemonics: assertion 'label != NULL' failed
Jun 30 21:35:12 Loki gnome-shell[1867]: pushModal: invocation of begin_modal failed
Jun 30 21:35:12 Loki gnome-shell[1867]: keyringPrompt: Failed to show modal dialog. Dismissing prompt request
Jun 30 21:35:12 Loki gpg-agent[4298]: failed to unprotect the secret key: Operation cancelled
Jun 30 21:35:12 Loki gpg-agent[4298]: failed to read the secret key
Jun 30 21:35:12 Loki gpg-agent[4298]: command 'PKDECRYPT' failed: Operation cancelled <Pinentry>
```

**Comment by maximbaz** [comment]
Unfortunately I don't know how I can help, it does seem the pinentry you are using is buggy. If you can set a different pinentry in `~/.gnupg/gpg-agent.conf` that will not crash, do so.

```
pinentry-program /path/to/different/pinentry
```
