### ISSUE TITLE
Navigate between password/login/otp using arrow keys

### ISSUE THREAD

**Issue by rbuzatu90** [browserpass/browserpass#267]
I think using arrow keys to select the desired field is way more intuitive then using ctrl/shift+c.
LastPass has this option and is very convenient.

**Comment by rbuzatu90** [comment]
If there is someone who's willing to implement this I'm willing to donate a few bucks as well for the effort :-)

**Comment by erayd** [comment]
We will implement this in v3. You don't need to pay us :-).

**Comment by rbuzatu90** [comment]
Hey thanks for such a quick reply! I saw the features planned for v3, but that might take a while and for me this feature would be so handy so get in it sooner would be great.

**Comment by erayd** [comment]
@rbuzatu90 Fair enough - have implemented this in v2 for you (#279).

**Comment by erayd** [comment]
@rbuzatu90 Also done for v3 in browserpass/browserpass-extension#23, if you want to try that version out.

**Comment by maximbaz** [comment]
Merged and released
