### ISSUE TITLE
Color code the badges

### ISSUE THREAD

**Issue by ipundit** [browserpass/browserpass#270]
### General information
* Operating system + version: Windows 10 64 bit
* Browser + version: Chrome 67.0.3396.99 64 bit
* Information about the host app:
  * How did you install it: Prebuilt binary
  * If installed an official release, put a version: 2.0.21
* Information about the browser extension: Chrome webstore

---

### Exact steps to reproduce the problem
1. Configure multiple Custom Store locations
   - Note that there is no option to choose a color
2. Browse to a site with multiple logins in your password store
3. Ctrl+Shift+L: See badges for each password store location
   - Note that all the badges are green

It would help the user to select which login to use if the badges were color coded, so I could have green badges for my personal logins, and red badges for my work logins.  The user could choose the badge color by specifying an RGB hex number, or by using a color picker.

This is what the result would look like:
![different colored badges](https://user-images.githubusercontent.com/4867876/42263410-8825a7d2-7fa0-11e8-8577-e8b1fa6e93fa.png)

**Comment by erayd** [comment]
@ipundit Good idea - we'll do this :-). In the middle of a v3 rewrite at the moment, so good timing.
