### ISSUE TITLE
Firefox not prompting for passphrase

### ISSUE THREAD

**Issue by JoakimLofgren** [browserpass/browserpass#281]
### General information

* Operating system + version: Ubuntu 18.04.1 
* Browser + version: Firefox 61.0.1 (64bit)
* Information about the host app:
  * How did you install it?
    I installed the pre-built binary (from the github releases page)
  * If installed an official release, put a version: 
    ```
    $ ./browserpass-linux64 -v
    Browserpass host app version: 2.0.22
    ```
* Information about the browser extension:
  * How did you install it? 
  Installed it from the Firefox addons: https://addons.mozilla.org/en-US/firefox/addon/browserpass-ce/
  * Browserpass extension version as reported by your browser: 2.0.22
---

### Exact steps to reproduce the problem
1. Ensure pass/gpg needs password to unlock key
2. Go to a login page you have credentials for
3. Ctrl + Shift + L and press enter (or click the browserpass icon and the fill form )

### What should happen?
It should prompt for my passphrase

### What happened instead?
Nothing

### Additional info
browser console has:
```
11:42:06.605 exit status 2
gpg: decryption failed: No secret key
background.js:70:13
11:42:06.605 stderr output from native app com.dannyvankooten.browserpass: [Browserpass] 2018/08/17 11:42:06 exit status 2
11:42:06.605 stderr output from native app com.dannyvankooten.browserpass: gpg: decryption failed: No secret key
```

```
$ gpg --version
gpg (GnuPG) 2.2.4
libgcrypt 1.8.1
...
```

Installing it for Chrome works, but not in Firefox.

**Comment by JoakimLofgren** [comment]
Is there a way to call the browserpass binary manually with what Firefox tries to send?
Enable debug output or constructing the input myself?

**Comment by maximbaz** [comment]
Closing as it seems there's nothing I can do, ping me if you find more details and especially if you discover that this is something we can fix in our code.

**Comment by maximbaz** [comment]
Just an idea, make sure pinentry application is properly configured in `gpg-agent.conf`, see this section of documentation for more info: https://github.com/browserpass/browserpass-native/#hints-for-configuring-gpg
