### ISSUE TITLE
New icon for the project

### ISSUE THREAD

**Issue by DamienCassou** [browserpass/browserpass#282]
Hi,

I'm the author of [passwe](https://gitlab.petton.fr/passwe/passwe-addon) a webextension that is doing the same thing as browserpass but with a bit less features. I have had a lot of fun creating this add-on but I plan on deprecating it as I prefer to use browserpass now.

Would you like browserpass to get passwe's icon?

![https://gitlab.petton.fr/uploads/-/system/project/avatar/52/border-128.png](https://gitlab.petton.fr/uploads/-/system/project/avatar/52/border-128.png)

![https://gitlab.petton.fr/uploads/-/system/project/avatar/53/passwe-app-128.png](https://gitlab.petton.fr/uploads/-/system/project/avatar/53/passwe-app-128.png)

![https://gitlab.petton.fr/passwe/passwe-addon/raw/master/media/screenshot-toolbar.png](https://gitlab.petton.fr/passwe/passwe-addon/raw/master/media/screenshot-toolbar.png)

If you like this icon better than your current one, I will create a PR.

@NicolasPetton is the author of the icon and agrees on giving it to browserpass.

**Comment by maximbaz** [comment]
Hey, thanks for the offer! 🙂 I like both the current and this one. 

On the one hand I already have two other browser extensions installed that also use fingerprint in their icons, on the other hand it shouldn't stop us from using a better icon if we like it 😉 

@erayd which one do you like more?

**Comment by erayd** [comment]
@maximbaz It's a nice icon, but I think I would prefer to avoid a fingerprint icon, as it implies biometrics, which isn't really anything to do with browserpass. As such, I think the current icon is better suited to the purpose of this extension.

With that said, I'd be quite happy for the project to have a new icon. A padlock is rather generic - something that more obviously indicates passwords, or a password manager, would be useful and improve the user experience.

**Comment by maximbaz** [comment]
OK, agreed to prefer the current icon over the icon with fingerprint in it. Thanks again @DamienCassou and @NicolasPetton for the offer!

We can keep this issue open for now to see if there are other suggestions for the icon, it would be good indeed to have a new icon to distinguish v2 from v3.

**Comment by maximbaz** [comment]
Interesting idea, but having ID card somehow doesn't click with me...

On that site I noticed a couple of interesting icons that give a hint of forms and passwords:

1. [one](https://www.iconfinder.com/icons/377865/password_icon)
![image](https://user-images.githubusercontent.com/1177900/46685748-83e4bf80-cbf6-11e8-8ee0-75418efc1e44.png)

2. [two](https://www.iconfinder.com/icons/628252/id_lock_pass_password_security_icon)
![image](https://user-images.githubusercontent.com/1177900/46685765-8fd08180-cbf6-11e8-8058-a687ecd6fb12.png)

I wanted to say that spending $2 for the license is manageable, but even the purchased license specifically prohibits using the icon as part of a logo 😕

**Comment by ajgrf** [comment]
I had another idea to use the letter P (for pass), but make the descender into a key. Something like this:

![browserpass_concept](https://user-images.githubusercontent.com/10733175/46686554-25184980-cbe8-11e8-9218-b402bb4aae50.jpg)

Obviously someone with better skills than me would have to pretty it up. Although it seems like maybe you guys want the icon to suggest the idea of passwords much more directly, rather than relying on a metaphor with physical objects.

**Comment by savyajha** [comment]
Fwiw, I think both variants look cool, with the capital variant looking better.

**Comment by richlewis42** [comment]
I actually prefer the lowercase thematically, as it fits with the command line `pass` which is in lower case.

**Comment by maximbaz** [comment]
Nice job @richlewis42 👍 Please do attach the SVGs, I would like to play around and see how these icons look in the browser. I'll most probably keep the current blue color (`#5f8dd3`), because black looks bad in browsers with dark theme while blue seems alright in both light and dark themes, but I can change the color myself 😉

**Comment by maximbaz** [comment]
A friendly ping @richlewis42 🙂

**Comment by richlewis42** [comment]
ah my bad, the machine the file is on died and I need to get the hd into its replacement - now is as good a time as any to do that, will get back later this eve

**Comment by richlewis42** [comment]
Well I got it sorted finally:  
[pass-logo.tar.gz](https://github.com/browserpass/browserpass/files/2979047/pass-logo.tar.gz)

**Comment by maximbaz** [comment]
Thanks a lot @lewisacidic!

I definitely want a new logo for v3, and my favorite is capital P. I have a couple of suggestions, in the current form it looks like this:

![image](https://user-images.githubusercontent.com/1177900/54563596-e2923e80-49c9-11e9-966a-3c4f6713b93c.png)

While it looks cool on the "chrome://extensions" page where I can see a larger icon, on the top panel I can barely recognize that it is a key (and I have a 4k screen), I'm afraid the majority of folks will think that it's a plain letter P without realizing that there is much more in the logo 😉 

Given that .png icon has to be a square size (128x128 px) anyway, can you try to make use of the available space on the sides and make "key" parts of the icon more... expressive?

My very crude demo of what I mean is below (please don't laugh 😛), I made the curve of the P as well as the left side thicker, it looks ugly when looking close:

![image](https://user-images.githubusercontent.com/1177900/54563762-5896a580-49ca-11e9-9941-02b37aaec8f7.png)

But when looking in a browser, especially in the top panel, I think it's more recognizable as a key:

![image](https://user-images.githubusercontent.com/1177900/54563526-b2e33680-49c9-11e9-92c0-c5e5d2e4693a.png)

**Comment by lewisacidic** [comment]
Sorry for the delay, lots going on on my end atm!! So I'm *really* not a designer, but I gave it another go, making it thicker, the key part longer, and a bit more pronounced.  Thoughts?

![pass-logo-candidate](https://user-images.githubusercontent.com/2941720/54957161-d8cc8600-4f49-11e9-843d-f0151d01514c.png)

[pass-logo-candidate.tar.gz](https://github.com/browserpass/browserpass/files/3005682/pass-logo-candidate.tar.gz)

**Comment by maximbaz** [comment]
I like it! I added it to Browserpass v3, [which is now available for testing](https://github.com/browserpass/browserpass/issues/331)! If you have time, please try it out, and tell me if you like this icon too (any other feedback is welcome as well).

**Comment by maximbaz** [comment]
I will close this since I don't think I'm going back to the lock icon, but if anyone has more ideas or feedback, please share 😉

**Comment by maximbaz** [comment]
And once again, thanks a lot everyone who participated, and especially @ajgrf for the idea and @lewisacidic for the implementation 🎉

**Comment by maximbaz** [comment]
Remember to check out https://github.com/browserpass/browserpass/issues/334 !
