### ISSUE TITLE
Ability to configure default username

### ISSUE THREAD

**Issue by anarcat** [browserpass/browserpass#289]
i use the same login name on most sites i'm on. for example here i am "anarcat". there are exceptions to the rule, naturally, but I would like it if I wouldn't have to specify that login name in *every* password I use and instead allow some default to be configured in the Browserpass configuration. it would greatly reduce the work I have to make automatic login work...

**Comment by maximbaz** [comment]
I like this idea, will be considered as part of v3.

**Comment by maximbaz** [comment]
Implemented in v3 😉 I'll push as 3.0.2 later tonight, see #331 if you already want to try
