### ISSUE TITLE
Indicate in the button the number of matching entries for the current URL

### ISSUE THREAD

**Issue by ajgrf** [browserpass/browserpass#292]
Bitwarden's browser extension changes its toolbar button to show the number of passwords that match the current tab. It would be nice to have this feature in browserpass too.

You can also find similar features in many other extensions like uBlock Origin, which shows the number of requests blocked in its toolbar icon.

**Comment by maximbaz** [comment]
Finally I got to play with this, turns out it's quite simple. See #331 for how to test this now, or wait a bit before I release v3 😉
