### ISSUE TITLE
Support brave browser with install.sh

### ISSUE THREAD

**Issue by mithodin** [browserpass/browserpass#294]
The brave browser (https://brave.com/) now supports chrome extensions in the beta release channel and will apparently also support them in the stable release once it hits 1.0.

That means it also supports browserpass (yay!).

Therefore, the install script should try to detect brave and give the option to install the native messaging host json file in the appropriate location. So far, I have only been able to find the system-wide folder it looks at via https://github.com/brave/muon/pull/259, but there should be an appropriate user location as well. If I manange to find out, I will update this issue.

**Comment by mithodin** [comment]
With the beta version of brave,  ~/.config/BraveSoftware/Brave-Browser-Beta seems to be the user path in linux.

**Comment by mithodin** [comment]
I have created a pull request implementing this. https://github.com/browserpass/browserpass/pull/295

**Comment by maximbaz** [comment]
Thanks for the PR, let's track this work via #295 then 👍
