### ISSUE TITLE
unable to find by "passwordstore" search request on addons.mozilla.org

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [browserpass/browserpass#298]
But it's the first by passwordstore.org request:

https://addons.mozilla.org/en-US/firefox/search/?platform=linux&q=passwordstore.org
https://addons.mozilla.org/en-US/firefox/search/?platform=linux&q=passwordstore

**Comment by maximbaz** [comment]
I did have "passwordstore" as a tag, but seems search doesn't respect that. Added some tags directly to the description, hope it will help. If you have other ideas what I should do, let me know 😉 

![image](https://user-images.githubusercontent.com/1177900/48197319-b698e980-e355-11e8-9176-d55744b570a5.png)
