### ISSUE TITLE
browserpass icon not showing in chromium

### ISSUE THREAD

**Issue by mstarodub** [browserpass/browserpass#301]
### General information

* Operating system + version: Ubuntu 16.04
* Browser + version: ungoogled-chromium 65.0
* Information about the host app:
  * How did you install it? ./install.sh
    * Installed via a package manager, downloaded a pre-built binary, compiled yourself? pre-built binary
  * If installed an official release, put a version: v2.0.22
    * In the recent versions it can be obtained with `$ browserpass -v` Browserpass host app version: 2.0.22
    * If in doubt what version you have, download and re-install the latest version!
  * If built from sources, put a commit id (`$ git describe --always`): 
* Information about the browser extension:
  * How did you install it? Downloaded seperately from the releases page (same version as the binary) prior to installing the host app, drag and drop into extensions page
    * Installed via webstore, downloaded a pre-built extension, compiled yourself? pre-built
  * Browserpass extension version as reported by your browser: 2.0.22

---

### Exact steps to reproduce the problem
1. Icon doesn't show, even after restarting chromium and rebooting
### What should happen?
The icon was visible before installing the host app

**Comment by maximbaz** [comment]
Hey, check if the extension is present and enabled on `chrome://extensions`, sounds like it was disabled maybe? Also, I have some icons hidden in the "three-dots" menu in Chromium, maybe browserpass is there for you:

![image](https://user-images.githubusercontent.com/1177900/49344866-ff09a580-f67c-11e8-8b52-dd8bf2c1c784.png)

**Comment by mstarodub** [comment]
I checked the three-dots-hidden-extension-menu, it's not there either.
Also it seems that the extension can't be manually enabled.
![browserpass](https://user-images.githubusercontent.com/23422754/49344910-ab4b8c00-f67d-11e8-9dcd-5b618f7fa621.png)

**Comment by erayd** [comment]
@mstarodub What happens when you attempt to check the 'enable' checkbox?

**Comment by mstarodub** [comment]
@erayd It does nothing / isn't clickable.

**Comment by mstarodub** [comment]
If there's any additional informaion required, please tell me the names of the relevant command outputs 
/ logfiles, so that I can post them.

**Comment by erayd** [comment]
@mstarodub Are you able to remove the manually-installed extension, and install it from the chrome store instead? Does that work?

**Comment by maximbaz** [comment]
Also try to remove the policy file, its location depends on what you chose in `./install.sh`, but this is the file - see where it got added and remove it.

https://github.com/browserpass/browserpass/blob/33d9be90d664362613f606914f603f8a9a0dcf3b/install.sh#L133

Policy is there to automatically install the extension for you from Chrome Webstore, if you don't want auto-updates and want to install extension manually, you don't need policy anyway.

**Comment by mstarodub** [comment]
@erayd I can't seem to remove it through normal means.
@maximbaz removed it, but so far nothing changed on the "extensions" page.

**Comment by mstarodub** [comment]
removed the entire folder, but weirdly, it's still there and I can't disable or remove it.

**Comment by maximbaz** [comment]
Double check that you found all locations where `chrome-policy.json` was installed, the message "extension is managed and cannot be removed" can only mean that the policy is active.

**Comment by mstarodub** [comment]
Thank you for your help. I made sure I deleted every file related to browserpass, and it worked after a reinstall. It seems like the issue was in installing the extension seperately from the releases page prior to installing the host application.
