### ISSUE TITLE
browserpass does not ask password to unlock password store

### ISSUE THREAD

**Issue by jack6000** [browserpass/browserpass#303]
### Exact steps to reproduce the problem
1. Run firefox
2. Click on browserpass-ce icon, search whatever site you have, and copy login or password

### What should happen?
A dialog asking me a password to unlock the store

### What happened instead?
Nothing, and no errors

But if use pass in the terminal, unlock my password store, close the terminal,  and run firefox again, then everything is fine.

My setup:
Ubuntu18.10
Browser pass 2.0.22 (from firefox store)
The host app was first installed from ubuntu-repo, but it s an old version and was not fully functionnal, so i have uninstalled it, and installed the latest one from github with install.sh script.

I tried also with Chromium, and everything is fine.

**Comment by maximbaz** [comment]
Hi there, I'm afraid it's not browserpass issue. Have a look at #266 or #281 😞
