### ISSUE TITLE
Segmentation violation when running `go test` on clean checkout

### ISSUE THREAD

**Issue by agboom** [browserpass/browserpass#304]
### General information
On a clean checkout of browserpass, the tests seem to fail with a segmentation violation.

### Exact steps to reproduce the problem
1. Clone master (reproduced on commit `33d9be9`)
2. Run `make`
3. `TestOtp` fails with segmentation violation ([full output here](https://pastebin.com/ZHc81Lbf))
4. Subsequent `go test` yields the same result

### What should happen?
The tests should succeed without segmentation violation

### Further information
I followed the installation steps in [CONTRIBUTING.md](https://github.com/browserpass/browserpass/blob/master/CONTRIBUTING.md)

Output of `go version`:
```
go version go1.11.2 linux/amd64
```

Output of `yarn --version`:
```
1.12.3
```

Output of `dep version`:
```
dep:
 version     : devel
 build date  : 
 git hash    : 
 go version  : go1.10.3
 go compiler : gc
 platform    : linux/amd64
 features    : ImportDuringSolve=false
```

**Comment by maximbaz** [comment]
Nice one :)
