### ISSUE TITLE
Add ability to see the stored password

### ISSUE THREAD

**Issue by mildred** [browserpass/browserpass#310]
This is a feature request.

Some sites (generally banking) do not allow entering the password via the keyboard or copy/paste. Instead they require you to click on numbers shown on the page at random locations to form a secret code.

It would be nice to be able to see the stored password document. Perhaps like PassFF does by hiding the first line (black text on black background) until the mouse is over the text.

Also, some other sites require you to type two different passwords, or two login codes. Having the ability to see the stored password document would help those edge cases

The window should stay on top even if defocused so it is still possible to see its content even when interacting with the web page.

**Comment by maximbaz** [comment]
Hey, sorry for the late reply, I completely missed this ticket.

To be honest I feel this is a very unusual and site-specific request, at the moment I don't think it fits Browserpass. You better off using something else to see a password, a dmenu/rofi script, or copy password to clipboard and open clipboard manager.

Filling two different passwords would be supported via #187.
