### ISSUE TITLE
Error: Unable to detect the location of gpg binary

### ISSUE THREAD

**Issue by siwan05** [browserpass/browserpass#311]
### General information

* Operating system + version: MacOS 10.14.2
* Browser + version: Chrome 71.0.3578.98
* Information about the host app:
  * How did you install it?
    * downloaded a pre-built binary
  * If installed an official release, put a version: 
    * 2.0.22
* Information about the browser extension:
  * How did you install it?
    * Installed via webstore
  * Browserpass extension version as reported by your browser: 2.0.22

---

### Exact steps to reproduce the problem
1. Go to page related to a stored password
2. Click the browserpass button:
![image](https://user-images.githubusercontent.com/6042171/51032025-da1f2100-159e-11e9-8406-db90d0f558a6.png)
2. Click the password you wish to use

### What should happen?
The password is copied
### What happened instead?
I get the following error:
![image](https://user-images.githubusercontent.com/6042171/51032094-0d61b000-159f-11e9-9af5-514396c2480d.png)

**Comment by maximbaz** [comment]
Hi there, have you already tried the steps from FAQ? https://github.com/browserpass/browserpass#does-not-work-on-macos-native-host-has-exited

**Comment by siwan05** [comment]
I thought I had but hadn't done all the steps. After following the steps my pass doesn't seem to work at all (not from terminal either). I get the following error:
`gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed
gpg: decryption failed: No secret key`

Any idea what is wrong? Thanks!

**Comment by maximbaz** [comment]
Try to restart gpg-agent, or maybe better simply reboot. After that make sure gpg itself is able to see your private key with `gpg -K`, if so proceed retrying pass and browserpass.

**Comment by siwan05** [comment]
Just tried restarting and then `gpg -K` but that just resulted in:
> gpg: can't connect to the agent: IPC connect call failed
> gpg: can't connect to the agent: IPC connect call failed
> gpg: can't connect to the agent: IPC connect call failed

Any other ideas?

**Comment by maximbaz** [comment]
Uh it seems you broke your gpg 😄 Try to google, there are some results like this: https://stackoverflow.com/questions/46673717/gpg-cant-connect-to-the-agent-ipc-connect-call-failed

Browserpass doesn't use `pass` at all, but it heavily depends on `gpg`, so you've got to get `gpg` working before you can use this project :)

**Comment by siwan05** [comment]
So I simply re-installed macgpg2 from `https://github.com/GPGTools/MacGPG2`, that fixed the issue. Not sure what I did to break it though!

browserpass also works now, thanks for the help :)

**Comment by maximbaz** [comment]
Yay, enjoy 😉
