### ISSUE TITLE
[Feature request] Add shortcut to copy OTP

### ISSUE THREAD

**Issue by apiraino** [browserpass/browserpass#314]
### General information

* Operating system + version: any
* Browser + version: any
* Browserpass extension version as reported by your browser: 2.0.22

---

First of all, thank you for this extension.

Now, unless I am mistaken, there is no keyboard shortcut to copy the OTP token; would it be possible to add it?

That would really speed up logins, as no mouse would be required:
- CTRL+SHIFT+L: raise browserpass
- fuzzy search: search for the pwd
- CTRL+SHIFT+O (example): copy the OTP, too

I'm aware that in referring to https://github.com/browserpass/browserpass/issues/256 you suggested an external script to do the job; a shortcut would be ... well ... shorter :-)

**Comment by vincentbernat** [comment]
Instead of copying, it would be great to insert the OTP into the currently focused field. This way, you don't need to involve the clipboard.

**Comment by maximbaz** [comment]
The entire OTP functionality will not be part of v3, sorry. I'll put up an explanation in README, but for now refer to #322.
