### ISSUE TITLE
Tor Browser Installation Issue

### ISSUE THREAD

**Issue by larry-beck** [browserpass/browserpass#316]
Issue when trying to get BrowserPass to work with Tor Browser, it give the following error when trying to search for site via browser extension, "Error: Attempt to postMessage on disconnected port"

Installed browser host app from github v.2.0.22, ran install.sh and selected Firefox since Tor Browser is based on Firefox build, however, it installs NativeMessagingHosts director and related .json file in the Mozilla folder under Application Support on macOS 10.14.3. I have the browser extension installed from Mozilla addon store, browserpass-ce 2.0.22

I have tried placing the NativeMessagingHosts folder and also the .json file in multiple folders and locations in the TorBrowser-Data directory under Application Support, but nothing works.

Any suggestions or help to get browserpass working within Tor Browser directly? 

Thank you!!

**Comment by maximbaz** [comment]
Hey, check with friendly folks in https://github.com/browserpass/browserpass/issues/199, I believe some of them managed to get it running in the Tor browser — just read what's there already and feel free to ask new questions. Additionally, if you manage to come up with a consistent set of installation steps that would work for all users of Tor browser, a PR for `install.sh` and/or `README.md` is very welcome 😉
