### ISSUE TITLE
Incompatible with latest Chromium (67); high CPU usage and freezing.

### ISSUE THREAD

**Issue by subdavis** [browserpass/browserpass#323]
### General information

* Operating system + version: Ubuntu 17.10 x86_64
* Browser + version: Chromium 67.0.3396.99-0ubuntu0.17.10.1
* Information about the host app:
  * How did you install it? 
    * pre-build from github releases
  * If installed an official release, put a version: 
    * 2.0.22
* Information about the browser extension:
  * How did you install it?
    * from chrome webstore
  * Browserpass extension version as reported by your browser: 

---

### Exact steps to reproduce the problem
1. Install versions described above.
2. Launch chromium
3. Open browser popup

### What should happen?

Normal operation

### What happened instead?

Browsepass Extension shows spinner indefinitely.  In `~$ top` the browsepass native host can be seen using 100-200% of CPU time.  If I don't pkill it, my whole system begins to freeze up.

Additional details:
The exact same versions work perfectly on the same machine, same native host with:

* Firefox 64.0
* Google Chrome Unstable Version 74.0.3710.0 (Official Build) dev (64-bit)

Happy to provide additional details.  I didn't see anything helpful in chrome's debug messages when run with `chromium-browser --enable-logging --v=1`

 Edit: Thank you for making this software.  It works splendidly on everything else.  Sometimes the ubiquity of free software makes me forget to say thanks :)

**Comment by maximbaz** [comment]
Hey, this is very weird, I cannot think of a simple explanation... Can you double-check that you have exactly the same settings in browserpass options? Maybe you are using a different set of password store locations?

The latest stable version of Chromium is 72 by the way, not 67 😉

**Comment by subdavis** [comment]
I encountered this on my first installation.  The settings are identical.  I only have 1 password store.

67 is what I get fresh from apt.

The chromium PPAs are a disaster and from Ubuntu forums, it looks like there are a half dozen unmaintained PPAs /rant

I'll try to get 72 installed and test with that one.  Have you tried to reproduce on 67?  I think it would be totally acceptable to just document browserpass as unsupported before version X if we can nail down where it breaks.

**Comment by maximbaz** [comment]
Interesting, no I haven't tried, I don't have an opportunity to test on older Chromium, please do try 72 and let me know if it works fine :)

> I think it would be totally acceptable to just document browserpass as unsupported before version X if we can nail down where it breaks.

README already says "A recent version of Chrome or Chromium", but to be honest we have no resources to commit to support previous versions of browsers, so in reality as soon as we learn that it doesn't work on some version, I'll probably change that line to "the latest version of Chrome and Chromium" :)

Having said that, I'm simply curious what's wrong because the code hasn't changed for a while in this repo and it definitely used to work on all previous versions of Chromium, including 67.

**Comment by subdavis** [comment]
Works on 71.  

But for the sake of maintainer time, latest sounds good to me.  I'm happy closing this issue, since anyone with similar problems should be able to discover it fairly easily.
