### ISSUE TITLE
Sometimes truncate password

### ISSUE THREAD

**Issue by michft** [browserpass/browserpass#325]
### General information

* Operating system + version:

Ubuntu 18.04.1 (xfce4 UI)

* Browser + version:

Firefox 65.0.1 (64Bit)

* Information about the host app:
  * How did you install it?

Followed online instructions

    * Installed via a package manager, downloaded a pre-built binary, compiled yourself?
  * If installed an official release, put a version: 
    * In the recent versions it can be obtained with `$ browserpass -v`.
    * If in doubt what version you have, download and re-install the latest version!
  * If built from sources, put a commit id (`$ git describe --always`): 
* Information about the browser extension:
  * How did you install it?

Clicked from Firefox add-ons page link.

    * Installed via webstore, downloaded a pre-built extension, compiled yourself?
  * Browserpass extension version as reported by your browser:

2.0.22

---

### Exact steps to reproduce the problem
1. Load a new Webpage
2. Click password on a long password
3. Password sometime truncates and only partially copies to clipboard

### What should happen?

Should get full password all the time

### What happened instead?

First few times may get password truncated at 10-14 chars seen as black circles. Have long password, AlphaNum only. Once password is correctly copying, can't get truncated password.

**Comment by maximbaz** [comment]
Hey @michft, please try to come up with a reproducible set of steps. Maybe it happens only on specific website? Or only with specific `pass` credentials? I've never experienced this issue, so I don't really know where to look for.

**Comment by maximbaz** [comment]
Closing as not reproducible, please share more details if you ever experience this again. There's also a new version of Browserpass, please test there too if you can: https://github.com/browserpass/browserpass/issues/331
