### ISSUE TITLE
CTRL+Shift+L not working for MacOS and Firefox Quantum

### ISSUE THREAD

**Issue by chrisalcantara** [browserpass/browserpass#326]
### General information

* Operating system + version: MacOS 10.12.6
* Browser + version: Firefox 65.0.1
* Information about the host app:
  * How did you install it?
    **I installed it via homebrew**
    
  * If installed an official release, put a version: 
    **Browserpass host app version: 2.0.22**
  
* Information about the browser extension:
  * How did you install it?
    **I installed the browserpass-ce add-on from the Firefox store**

  * Browserpass extension version as reported by your browser: 2.0.22

---

### Exact steps to reproduce the problem
1. Open firefox in MacOS with latest browserpass-ce addon
2. Go to website with password prompt
3. Hit CTRL+SHIFT+L

### What should happen?

Password prompt should appear

### What happened instead?

Noting

### Description

I've gone through the issues in this repo but yet to see anything about CTRL+SHIFT+L not working in Firefox Quantum in MacOS, especially 10.12+. 

I tried this addon in chromium, and the shortcut works, meaning the OS isn't hogging the key. I have an Arch-based machine at home, and the shortcut works.

I went through the process mentioned in #185 of downloading the add-on, changing the `manifest.json` to another shortcut, but everytime I zip it  and  load it into Firefox, the browser says the entire folder is corrupted. Not sure what the problem is because I'm literally changing one letter in the json file.

Any help would be great. Thanks for this great tool.

**Comment by chrisalcantara** [comment]
Firefox 66.0 now [allows custom keyboard shortcuts](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox) for various extensions. I was FINALLY able to change my to ctrl+shift+L for browserpass, and it works.

**Comment by maximbaz** [comment]
What a great news! Sorry I didn't reply sooner, I don't have a macOS to try, but I'm glad it's all solved now.
