### ISSUE TITLE
Page requesting three values as credentials

### ISSUE THREAD

**Issue by gurucubano** [browserpass/browserpass#327]
### General information

* Operating system + version: FreeBSD 13.0 CURRENT
* Browser + version: FF 64.0
* Information about the host app:
  * How did you install it?
    * Installed via a package manager, downloaded a pre-built binary, compiled yourself?
Compiled by my own.
  
This is perhaps more a question or an issue with the password store:
I have a web site requesting as credentials in three fields: Name, Surname, Password.
How the entry in the file of the password storage should look like?
```
password
Username: Surname
Name
```
does not work.

**Comment by maximbaz** [comment]
Hey, this is currently not supported, and I'm not sure yet how this will look like, but I'm tracking it under https://github.com/browserpass/browserpass/issues/187, so I'll close this as duplicate.

Can you share the link to this website? It will help us testing the feature, whenever it gets implemented.

**Comment by gurucubano** [comment]
Thanks. I will share the URL in #187.
