### ISSUE TITLE
Add ability to store multiple URL for one username

### ISSUE THREAD

**Issue by bilyboy785** [browserpass/browserpass#329]
Hello !

Could it be possible to store multiple URLs for a couple of User/Password ?

**Comment by maximbaz** [comment]
Hey, yes it is possible. I've just published a pre-release version of Browserpass v3, if you can, please go ahead and test it - https://github.com/browserpass/browserpass/issues/331.

What you are looking for is documented here: https://github.com/browserpass/browserpass-extension#how-to-use-the-same-username-and-password-pair-on-multiple-domains

If you can't try v3 yet, the "second option" described in that section (symlinks) is also supported in the current Browserpass v2.
