### ISSUE TITLE
Shortcut stopped working on Vivaldi

### ISSUE THREAD

**Issue by cryzed** [browserpass/browserpass#332]
### General information

* Operating system + version: Arch Linux, up-to-date on 30.03.2019
* Browser + version: Vivaldi 2.4.1488.35
* Information about the host app:
  * How did you install it?: Package manager (AUR)
  * If installed an official release, put a version: `Browserpass host app version: 2.0.21`
* Information about the browser extension:
  * How did you install it?
    * Installed through the AUR package, as a policy
  * Browserpass extension version as reported by your browser: 2.0.22

---

### Exact steps to reproduce the problem
1. Install browserpass using Vivaldi
2. Try to trigger the popup using Ctrl+Shift+L

### What should happen?
The selection popup should open.

### What happened instead?
The selection popup doesn't open.

I hope you can take a look at this, this seems to have broken with the last Vivaldi update.

**Comment by maximbaz** [comment]
Sorry I don't use Vivaldi, so I can only give some generic advices for you to try. Since it's based on Chromium, does it have `chrome://extensions/shortcuts`, and if so, can you confirm that you see Browserpass shortcut there? If not, try to set it there.

![image](https://user-images.githubusercontent.com/1177900/55278941-1a2ab000-5313-11e9-9482-f615a6bdff9c.png)

**Comment by cryzed** [comment]
I understand, thanks for the feedback. Yes, it's definitely listed there:

![test](https://i.imgur.com/DKFKmrh.png). I might try taking it up with the Vivaldi developers then. Unfortunate.

**Comment by cryzed** [comment]
Yeah, seems like it's Vivaldi's fault, I'm not [the only one](https://forum.vivaldi.net/topic/36023/extension-shortcut-not-working-on-2-4). Thanks for the reply!

**Comment by maximbaz** [comment]
Gotcha 👍 

By the way, if you can test the next major version of browserpass, please have a look in https://github.com/browserpass/browserpass/issues/331 😉 In particular, I'm curious if I guessed the configuration files for Vivaldi correctly:

https://github.com/browserpass/browserpass-native/blob/8411954b5a38ed7ed78aad2036e0bebdebfa982f/Makefile#L132-L154
https://github.com/browserpass/browserpass-native/blob/8411954b5a38ed7ed78aad2036e0bebdebfa982f/Makefile#L254-L276
