### ISSUE TITLE
New Logo Proposal 

### ISSUE THREAD

**Issue by Tobaloidee** [browserpass/browserpass#334]
Hi @maximbaz  Here's what I came up with! open for suggestions still.. 👍 

![BROWSERPASS ALL-02](https://user-images.githubusercontent.com/36028424/55679799-6c3b8900-5944-11e9-9cc1-7b429618029a.png)
![BROWSERPASS ALL-03](https://user-images.githubusercontent.com/36028424/55679804-7198d380-5944-11e9-814e-d9de8f62200c.png)

**Comment by erayd** [comment]
@Tobaloidee I *really* like these - they look amazing. Thank you!

My favourites are variation #1, and the first logotype in the list. @maximbaz - perhaps we could use variation #1 normally, and switch to #3 if a problem is present (e.g. fill error, host app outdated etc.)?

**Comment by erayd** [comment]
@Tobaloidee One thought - is there any chance you'd be willing to do an alternate version with exaggerated teeth on the key? At very small sizes, it looks a bit like a question mark.

**Comment by Tobaloidee** [comment]
Thanks @erayd 😃 you are welcome!

**Comment by Tobaloidee** [comment]
I updated the previous presentation above.. 👍

**Comment by erayd** [comment]
@Tobaloidee That looks great - thanks :smile:.

I think I still like your original one for most sizes, and the updated one for small sizes. @maximbaz - your thoughts?

**Comment by Tobaloidee** [comment]
for me this first version with a little adjustment 👍 
![BROWSERPASS ALL-04](https://user-images.githubusercontent.com/36028424/55680937-f8ed4380-5952-11e9-95eb-237fc6423f14.png)

**Comment by maximbaz** [comment]
@Tobaloidee amazing work, thanks so much!

Circular icon is a good call, agree 👍 

I must say I like the "filled" versions more than white circles with borders, looks more "modern" in my eyes 🙂 

![image](https://user-images.githubusercontent.com/1177900/55681641-d2b2ae00-5928-11e9-8dff-bfbac7c3e352.png)

![image](https://user-images.githubusercontent.com/1177900/55681647-f2e26d00-5928-11e9-8233-7fbc2bae8a53.png)

Adjusted version 1 makes the icon look less than a question mark, however it also loses the resemblance with the "P" letter:

![image](https://user-images.githubusercontent.com/1177900/55681651-16a5b300-5929-11e9-8b85-eda71b6a14b0.png)

We might want to exaggerate the features of the key a bit more, to make it recognizable when it's very small (example below):

![image](https://user-images.githubusercontent.com/1177900/55681863-b6644080-592b-11e9-991b-7411effeed43.png)

------------

In general I think the current shape will always resemble question mark more than letter P... I had some ideas how to approach this:

1. Try to enforce the letter "P", maybe by introducing more asymmetry (example below, it's just an idea)

![image](https://user-images.githubusercontent.com/1177900/55681768-78b2e800-592a-11e9-9dac-edfaa08cd7bc.png)

2. Keep the icon as it is, but enforce the resemblance in the logotype (example below, again it's just an idea):

![image](https://user-images.githubusercontent.com/1177900/55681826-08f12d00-592b-11e9-8624-bdacef4ca9df.png)

Maybe we could even use both of these ideas, introduce just a liiiitle bit of asymmetry and use the letter "P" in the logotype in the word "BrowserPass" that is similar to the "P" in the logomark...

---------------

One final minor annoyance is that Firefox places counter on top, which basically covers parts of the "P", but I don't think we can do anything about it 🙂

![image](https://user-images.githubusercontent.com/1177900/55681919-80738c00-592c-11e9-8655-76b6ca6bb328.png)

----------

What do you think? I'm not a designer after all, so not sure that my proposed solutions are good @Tobaloidee, but at least I tried to highlight the areas for improvement 🙂 

cc @532910, you wanted a ping when the new logo proposal is available.

**Comment by 532910** [comment]
It's really hard to see letter P in the
![image](https://user-images.githubusercontent.com/14617699/55682056-a56cfc80-5936-11e9-9bb4-82ef3a2ee104.png)

![image](https://user-images.githubusercontent.com/14617699/55682068-bc135380-5936-11e9-8e17-09822273129f.png)
looks significant better

I'm for removing the left part totally, something like this:
![image](https://user-images.githubusercontent.com/14617699/55682138-e6194580-5937-11e9-997f-1396f014a96f.png)

**Comment by erayd** [comment]
@532910 I see where you're coming from, but I think we do need to keep at least some of the left part. That top portion is critical to keeping its 'key-ness' at smaller sizes.

**Comment by Tobaloidee** [comment]
I will try some adjustments to it @maximbaz  👍

**Comment by 532910** [comment]
Really the icon 
![image](https://user-images.githubusercontent.com/14617699/55682842-5f696600-5941-11e9-80d6-19b79da84d4c.png)
I like more, than this proposal

But it should be cleaned, something like this:
![image](https://user-images.githubusercontent.com/14617699/55682956-b15ebb80-5942-11e9-8b02-33e4e31a13c0.png)

**Comment by Tobaloidee** [comment]
I did a new concept a while ago..just finished now

![new concept-05](https://user-images.githubusercontent.com/36028424/55683257-6491d980-5970-11e9-9080-be47bca60ed7.png)

**Comment by 532910** [comment]
looks better, but the tiny icons is unreadable
could you show 32px icon that is used on the browser's panel

**Comment by Tobaloidee** [comment]
![32x32](https://user-images.githubusercontent.com/36028424/55683365-72942a00-5971-11e9-9970-4a35848e601b.png)

**Comment by 532910** [comment]
vertical line and key bit are bad visible on 32 icons, could you emphasize them?

**Comment by maximbaz** [comment]
Wooooow @Tobaloidee, this is very, very interesting concept! But I agree, it suffers from the same problem as our previous logo: the large icon looks cool, but the small variant loses details. I found that the best approach would actually be to have two different logos, a large one (keep the current one) and a small one with exaggerated features (for example more visible key teeth).

To illustrate the concept, right now this is the large icon:

![image](https://user-images.githubusercontent.com/1177900/55683836-9ab96400-5944-11e9-9fa2-6ef5e3b7bf8e.png)

And this is a small icon:

![image](https://user-images.githubusercontent.com/1177900/55683846-a3119f00-5944-11e9-9665-7325201d262f.png)

Would you be able to do something about the small icon?

**Comment by Tobaloidee** [comment]
still working on that 32x32 visibility :)

**Comment by Tobaloidee** [comment]
![KEY 32x32](https://user-images.githubusercontent.com/36028424/55684461-41215b80-597d-11e9-973b-ef04029b3a3c.png)

**Comment by maximbaz** [comment]
I think it looks juuuust awesome, love it ❤️ 

![image](https://user-images.githubusercontent.com/1177900/55684586-dce6a380-594c-11e9-9a11-cda9c5fcb9ab.png)

I think we should keep the original (with 3 small teeth) for a big icon, and this one (with 2 large teeth) for a small icon.

---------

Let's try to address @532910's comment in another thread about the choice of color.  We can't possibly support all browser color schemes, so let's focus on making the icon to look good in the following selected list of environments:

1. White background (usual Chrome theme):

![image](https://user-images.githubusercontent.com/1177900/55684637-c68d1780-594d-11e9-8052-7ee244013677.png)

2. White background, popup active:

![image](https://user-images.githubusercontent.com/1177900/55684656-f0463e80-594d-11e9-9a8d-8e2b4383371d.png)

3. Dark background in Chrome:

![image](https://user-images.githubusercontent.com/1177900/55684669-2c799f00-594e-11e9-85f6-9065898a1d03.png)

4. Dark background, popup active:

![image](https://user-images.githubusercontent.com/1177900/55684672-38656100-594e-11e9-8402-f54f1ae93111.png)

5. Dark background in Firefox:

![image](https://user-images.githubusercontent.com/1177900/55684676-461ae680-594e-11e9-856f-c6b59b0610ff.png)

6. Dark background in Firefox, popup active:

![image](https://user-images.githubusercontent.com/1177900/55684679-53d06c00-594e-11e9-8e10-364c531656b6.png)

In my mind, all look good except the last example. @Tobaloidee can you think of some colors that in your opinion will look even better on all these 6 examples?

If you can attach a few examples with different colors, please attach them in the format like you did in this message, with small icons in different files, this way it's very easy for me to quickly load them in the browser for testing

![image](https://user-images.githubusercontent.com/1177900/55684706-a742ba00-594e-11e9-8d18-78fced0e57f8.png)

**Comment by Tobaloidee** [comment]
Ill give you some color variations..👍

**Comment by Tobaloidee** [comment]
![32x32 samples-01](https://user-images.githubusercontent.com/36028424/55684929-7335bc00-5983-11e9-94a0-76e9dd571f58.png)
![32x32 samples-02](https://user-images.githubusercontent.com/36028424/55684931-7630ac80-5983-11e9-9636-8aad2793609c.png)
![32x32 samples-03](https://user-images.githubusercontent.com/36028424/55684934-78930680-5983-11e9-8544-ef63995e96c0.png)
![32x32 samples-04](https://user-images.githubusercontent.com/36028424/55684938-7df05100-5983-11e9-8769-9427c8f98f83.png)
![32x32 samples-05](https://user-images.githubusercontent.com/36028424/55684941-847ec880-5983-11e9-8b2b-8096ab61d811.png)
![32x32 samples-06](https://user-images.githubusercontent.com/36028424/55684944-8779b900-5983-11e9-9a59-ae7aff829a2d.png)
![32x32 samples-07](https://user-images.githubusercontent.com/36028424/55684945-89dc1300-5983-11e9-9255-32f4ab1f1058.png)
![32x32 samples-08](https://user-images.githubusercontent.com/36028424/55684946-8ba5d680-5983-11e9-99fb-7fc8ee2e78eb.png)
![32x32 samples-09](https://user-images.githubusercontent.com/36028424/55684947-8e083080-5983-11e9-8a46-dc10f1e08535.png)
![32x32 samples-10](https://user-images.githubusercontent.com/36028424/55684948-906a8a80-5983-11e9-8b0a-6e8d07986797.png)

Personally I am biased to orange coz its my favorite color ryt now..hehe..still depends on you Sir..

**Comment by maximbaz** [comment]
Thank you! It was a very difficult decision, as all colors are very beautiful 🙂 

I'll go with dark green color, it is quite unique (in my experience red and blue are very common colors), it doesn't scream for attention and it yet it is distinctly visible everywhere:

-------

![image](https://user-images.githubusercontent.com/1177900/55685716-ce52b900-5959-11e9-81e2-f44ac5775918.png)

-----------

![image](https://user-images.githubusercontent.com/1177900/55685728-e0ccf280-5959-11e9-9189-39dc3b1daadd.png)

-----------

![image](https://user-images.githubusercontent.com/1177900/55685721-d14da980-5959-11e9-9146-733c02d09467.png)

--------------

![image](https://user-images.githubusercontent.com/1177900/55685739-f80be000-5959-11e9-9625-c8271f940eb9.png)

--------------

![image](https://user-images.githubusercontent.com/1177900/55685740-04903880-595a-11e9-87b8-c677c6def802.png)

----------

![image](https://user-images.githubusercontent.com/1177900/55685712-c72bab00-5959-11e9-9ce1-0d599006f6b6.png)

--------------------


@Tobaloidee could you please prepare a PR with the icons? 🙂 

I need to investigate a bit more the exact sizes that browser extension needs (since we are doing icons, let's make it properly). But until then, to make it simpler for you... could you open the PR in [browserpass-extension](https://github.com/browserpass/browserpass-extension/) repo, and put the icons in `src/icons/` folder in the following formats:

```
src/
  icons/
    big/
      logo-large.svg // below icons based on this
      logo128.png
      logo64.png
      logo48.png

      logo-small.svg // below icons based on this
      logo32.png
      logo16.png
images/
  logotype.svg
  logotype.png // to use in README.md
```

(by the way, are you OK with providing `.svg`? I was only thinking this would be useful in case we ever want to change colors later on. But if not, keep only `.png`)

Once you create a PR, I'll push to your branch to include correct icons in correct locations in the code 😉 

And once again, enormous thank you!! 🎉 

By the way, if you want to be mentioned as the author of the icons, feel free to put this in README.md as well!

**Comment by 532910** [comment]
New icon looks very nice and dark green looks good on all specified backgrounds!

**Comment by Tobaloidee** [comment]
Hi @maximbaz  i've created a PR #77 on BrowserPass-Extension just now with the logos & readme update

**Comment by Tobaloidee** [comment]
I have finalized all the logo files and different variations and formats of the logo..You can download it all from this [LINK](https://drive.google.com/drive/u/1/folders/1_eaWjv7GaZRcZWCim1YNUKKcv1h-cap3) to my drive.. Thanks a lot for accepting my design! Best regards to the project and see you around.. :) 

- Tobaloidee

**Comment by maximbaz** [comment]
Beautiful work @Tobaloidee, thank you so much!

**Comment by erayd** [comment]
Yes, thanks @Tobaloidee - it looks amazing!

**Comment by maximbaz** [comment]
Hey @Tobaloidee, could you please put the logo with 3 key teeth in your folder on Google Drive as well (the one below, but in dark-green color)? I could find it in "Logotype VERSION 2 Option" folder, but has "BrowserPass" text there, and I want to have it separately as well.

Ideally in both SVG and PNG formats in all sizes, just like you have in "ICON SIZE VARIATIONS" folder, but a single SVG in 500x500px would be enough as well, I can save the other sizes and convert to PNG myself!

![image](https://user-images.githubusercontent.com/1177900/55737564-b34d7b00-5a25-11e9-920c-230bb6bc173d.png)

I would simply like to use both logos, on small sizes I will use the logo with 2 key teeth, but on large sizes I will use the logo with 3 teeth 😉 

Just put it them in your Google Drive, I'll take care of moving them to the repo 👍

**Comment by 532910** [comment]
I'm sorry, but small 16px icon looks ugly. You can't just get svg and render it into 16px image. All small icons must be manually pixel-drown.
Compare:
old icon:
![image](https://user-images.githubusercontent.com/14617699/55682842-5f696600-5941-11e9-80d6-19b79da84d4c.png)

some my pixel correction (i'm not a designer)
![image](https://user-images.githubusercontent.com/14617699/55682956-b15ebb80-5942-11e9-8b02-33e4e31a13c0.png)

current icon:
![image](https://user-images.githubusercontent.com/14617699/55815768-84a0d480-5af9-11e9-8312-3162d8f58aab.png)

Even on the old icon i can see key bit.

**Comment by 532910** [comment]
same, 4x scaled:
![image](https://user-images.githubusercontent.com/14617699/55816399-dac24780-5afa-11e9-81f0-cafe5c0b7a31.png)
![image](https://user-images.githubusercontent.com/14617699/55816403-ddbd3800-5afa-11e9-86cb-fa27570a1ffe.png)
![image](https://user-images.githubusercontent.com/14617699/55816410-df86fb80-5afa-11e9-8d78-354d76ac7e60.png)

**Comment by max-baz** [comment]
That's a bit disappointing, on my screen a 32px icon gets picked up and it looks quite good. As much as I would like to keep using vector SVG in Firefox, if someone could draw a 16x16.png that is significantly better, I'll take it in instead of the SVG 👍

**Comment by 532910** [comment]
32px looks good, 16px are not.

**Comment by Tobaloidee** [comment]
I edited the 16x16px version. I made the key bigger. I uploaded the svg and png of it. :)

![16x16](https://user-images.githubusercontent.com/36028424/55895723-52719e80-5bef-11e9-93a0-90b13ba51b7b.png)

**Comment by max-baz** [comment]
You are awesome! 👍

**Comment by max-baz** [comment]
@532910 before I make a release, could you give it a quick try in any browser and tell me if you like this new icon more and we should go with it?

[browserpass-chromium-HEAD.zip](https://github.com/browserpass/browserpass/files/3065425/browserpass-chromium-HEAD.zip)
[browserpass-firefox-HEAD.zip](https://github.com/browserpass/browserpass/files/3065426/browserpass-firefox-HEAD.zip)

**Comment by max-baz** [comment]
I have heard a feedback that this is too big/bold icon and they would actually prefer the current one, which is blurry, but in style with the rest of the other browser extensions they have, that's why I wanted your opinion as well.

**Comment by max-baz** [comment]
I feel bad asking Tobaloidee to change 16px logo again, we are probably the pickiest crowd they have ever seen on the internet 😂

**Comment by 532910** [comment]
sorry, new one looks worse than before

**Comment by max-baz** [comment]
is your reasoning the same as I heard from someone else, about the key being too bold / big? Just want to understand if there is something to improve or you don't like the logo in general 😉

**Comment by 532910** [comment]
keys become too narrow, whole icon become oval
the icon blurry, it doesn't look like a pixel drown

**Comment by erayd** [comment]
For what it's worth, I actually quite like the existing small logo, and I don't think it needs changing. The key is clearly and obviously a key, albeit mainly identifiable by the head rather than the teeth. However, it's worth noting that I'm looking at it on a high-dpi screen (retina macbook); I don't know whether I would feel the same on something with a lower pixel density.

**Comment by max-baz** [comment]
I tend to feel the same, even though it is a bit blurry on low DPI screens, it is unique and recognizable, and you will know the meaning of the icon anyway because you'll see it elsewhere in a larger size, on Github or Web store. 

Not to offend anyone, but in hopefully near future there will be very few low DPI screens left anyway 😄

**Comment by 532910** [comment]
I believe that you see 32px (or bigger) instead of 16px icon on hiDPI. Could you make a screenshot?
Yes, I hope loDPI will die. Really it has already died on mobiles screens and partially on laptops. But loDPI will not die soon on  desktop. Not in the next 5 years.

Yes, the icon is unique but it's not recognizable. I see it in the large size extremely rare, almost never.  But 16px I see every moment that I see the browser window, almost permanent.

**Comment by max-baz** [comment]
by recognizable I meant distinguishable from other icons :) how many of other extensions you have provide pixel drawn icon? 

regardless, to be honest I'm inclined to say "it's good enough" and keep the current icon, in the end we are not specializing in drawing icons here, we do password management, so it doesn't have to be perfect :)

**Comment by erayd** [comment]
> I believe that you see 32px (or bigger) instead of 16px icon on hiDPI. Could you make a screenshot?

No problem - here are two, one focusing on the area in question, and a larger one showing it in the context of the rest of the browser. Note that I don't run my UI in a typical high-dpi configuration; my UI elements are all set extremely small. The entire green section of the browserpass icon in my screenshots is only 2.5mm across.

![scr-20190411-223605](https://user-images.githubusercontent.com/121486/55951336-1996ff80-5cab-11e9-9c37-c5df637a483b.png)
![scr-20190411-223707](https://user-images.githubusercontent.com/121486/55951340-1bf95980-5cab-11e9-89de-bc4f3bf6a5ba.png)

**Comment by 532910** [comment]
Hmm, our icons look different:
yours: 
![image](https://user-images.githubusercontent.com/14617699/56443939-57290780-62ff-11e9-884b-11d07dd51777.png)
![image](https://user-images.githubusercontent.com/14617699/56443957-6f008b80-62ff-11e9-8e7b-567896bdf77b.png)

mine:
![image](https://user-images.githubusercontent.com/14617699/56443941-5b552500-62ff-11e9-8723-cdf0f24b7cf3.png)
![image](https://user-images.githubusercontent.com/14617699/56443963-71fb7c00-62ff-11e9-896f-08561c11313c.png)

**Comment by 532910** [comment]
> how many of other extensions you have provide pixel drawn icon?

I'm sure all excellent small icons are pixel drawn.

![image](https://user-images.githubusercontent.com/14617699/56444995-c4d73280-6303-11e9-94d2-c5beaccad0f9.png)
![image](https://user-images.githubusercontent.com/14617699/56445006-d1f42180-6303-11e9-876a-29c5bd24412e.png)

**Comment by 532910** [comment]
BTW, 32px browserpass icon on 45" TV panel looks fine.

**Comment by Tobaloidee** [comment]
Hi Guys, I pixel drawn the 16x16 icon..I uploaded it in my shared drive for download. @maximbaz 

![16x16](https://user-images.githubusercontent.com/36028424/56456261-70cc5c80-639c-11e9-8957-16ebfe3a10b8.png)

![compare](https://user-images.githubusercontent.com/36028424/56456314-07008280-639d-11e9-9e39-be8c45ec856b.png)

**Comment by max-baz** [comment]
Thanks! @532910 are you satisfied with this icon? 🙂 

[browserpass-firefox-HEAD.zip](https://github.com/browserpass/browserpass-legacy/files/3099988/browserpass-firefox-HEAD.zip)

**Comment by 532910** [comment]
Much better, but I'm not satisfied sorry ):
1. Gimp says it has "an embedded color profile" and asks to convert it. The result depens on the option I choose.
2. Quite all icons I showed have gradient pixels. Such pixels should be added to make icon smooth.

**Comment by max-baz** [comment]
1. Can you try it in the browser by loading the extension itself? Embedded color profile usually means the colors are guaranteed to look as closely as possible to the designer's screen, AFAIK it's preferable to have it embedded.

**Comment by 532910** [comment]
I tried. It looks much better, but it's oversharped now and should be smoothed: "Quite all icons I showed have gradient pixels. Such pixels should be added to make icon smooth."

Embedded color profile usually means you have no guarantee the client will support it. Moreover gimp shows there are 4 different options to render it, so no guarantee the client will choose the proper one.

**Comment by max-baz** [comment]
> Embedded color profile usually means you have no guarantee the client will support it. 

If the latest Chromium and Firefox show proper colors, I think we are good 😉 

> I tried. It looks much better, but it's oversharped now and should be smoothed: "Quite all icons I showed have gradient pixels. Such pixels should be added to make icon smooth."

OK will wait if @Tobaloidee is kind enough and has time to give it another shot 🙏

**Comment by Tobaloidee** [comment]
I updated my drive again

**Comment by 532910** [comment]
@Tobaloidee, could you give a link to your drive?

**Comment by max-baz** [comment]
https://drive.google.com/drive/u/0/folders/1IfctztsVywDxGdTOppXmcpLtk_CNlTVX

@532910 do you want me to make a test build for you?

**Comment by Tobaloidee** [comment]
I made version b also with a subtle changes from the old pixels

**Comment by Tobaloidee** [comment]
https://drive.google.com/drive/u/1/folders/1IfctztsVywDxGdTOppXmcpLtk_CNlTVX

**Comment by 532910** [comment]
Hmm. I can't say it's ideal, but surely it's the best of all previous ones.

But the color profile is still present. Moreover it has Hewlett-Packard Copyright. And all other png's has no embedded color profile.

**Comment by Tobaloidee** [comment]
i added version C & D also just now

**Comment by 532910** [comment]
the current one, B, C, D, mine

![image](https://user-images.githubusercontent.com/14617699/56456944-318e1380-637c-11e9-882a-248e11a2ee6a.png)

![image](https://user-images.githubusercontent.com/14617699/56456947-3783f480-637c-11e9-805e-4beec35aa2bf.png)

Note, github sets wrong size for images. Click the image to see it in original size.

**Comment by max-baz** [comment]
is B the best? It's difficult for me to judge 🙂

**Comment by 532910** [comment]
I think mine of course (:

A bit corrected:
![image](https://user-images.githubusercontent.com/14617699/56457492-52f2fd80-6384-11e9-94d1-cdd0b5353093.png)

**Comment by max-baz** [comment]
I know one other person who doesn't have HiDPI screen, I have sent them the builds of -b, -c, -d and yours, I'll let you know what they think once I hear back :D

**Comment by max-baz** [comment]
@532910 your icon has won the contest, [I have added it to the repo](https://github.com/browserpass/browserpass-extension/commit/150e342522d673f628b01538fef7a5bd0123c300), thanks again to all of you for caring enough about this and pushing for making it happen!

**Comment by 532910** [comment]
I will reveal a secret, the icon is manually pixel-corrected, but the main work were done by gimp's NoHaLo/LoHaLo algorithms.
